AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: CD Demo Lambda
Resources:
  photoSearch:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 390
      Role: 'arn:aws:iam::567441204406:role/service-role/photoSearch-role-50a1gxhn'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
        Api2:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
        Api3:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
        Api4:
          Type: Api
          Properties:
            Path: /search
            Method: GET
        Api5:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
        Api6:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
      Layers:
        - >-
          arn:aws:lambda:us-east-1:770693421928:layer:Klayers-python38-aws-requests-auth:7
        - >-
          arn:aws:lambda:us-east-1:770693421928:layer:Klayers-python38-elasticsearch:19
        - >-
          arn:aws:lambda:us-east-1:770693421928:layer:Klayers-python38-requests:15

  indexphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 180
      Role: 'arn:aws:iam::567441204406:role/service-role/index-photos-role'
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - 's3:ObjectCreated:*'
      Layers:
        - >-
          arn:aws:lambda:us-east-1:770693421928:layer:Klayers-python38-requests:15
        - >-
          arn:aws:lambda:us-east-1:770693421928:layer:Klayers-python38-aws-requests-auth:7
        - >-
          arn:aws:lambda:us-east-1:770693421928:layer:Klayers-python38-elasticsearch:19
  Bucket1:
    Type: 'AWS::S3::Bucket'

